---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action ðŸ§ª'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Vault JSON is a secret; no access on pull requests
  # Testing can only be performed once code is merged
  push:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10 # Increase this timeout value as needed
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Perform setup prior to running test(s)
      - name: 'Testing setup step'
        shell: bash
        run: |
          # Testing setup step
          echo "Testing setup step"
          echo "Testing setup step/summary output" >> "$GITHUB_STEP_SUMMARY"

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          vault_mapping_json: ${{ secrets.VAULT_MAPPING_JSON }}
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: 'Check SHA1SUM of retrieved credential'
        shell: bash
        env:
          CREDENTIAL: ${{ env.CREDENTIAL }}
        # yamllint disable rule:line-length
        run: |
          # We test that the credential SHA1SUM is valid
          # This is obtained using:
          # CREDENTIAL_SHA1SUM=$(echo -n "$CREDENTIAL" | sha1sum | awk '{print $1}')
          CREDENTIAL_SHA1SUM=$(echo -n "$CREDENTIAL" | sha1sum | awk '{print $1}')
          if [ "$CREDENTIAL_SHA1SUM" == "c78aa738682ce8468b3869c035d207e3c7eb8a9f" ]; \
            then
              echo "Credential SHA1SUM validated âœ…"
            else
              echo "Credential SHA1SUM validation failed âŒ"
              echo "Expected: c78aa738682ce8468b3869c035d207e3c7eb8a9f"
              echo "Got: $CREDENTIAL_SHA1SUM"
              exit 1
            fi
          echo 'Local action test passed âœ…' >> "$GITHUB_STEP_SUMMARY"
        # yamllint enable rule:line-length

      - name: 'Verify failure with bogus credential path'
        uses: ./
        id: failure
        continue-on-error: true
        with:
          vault_mapping_json: ${{ secrets.VAULT_MAPPING_JSON }}
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          credential: "op://6n4qm2onchsinyyeuxmcfbo7ne/bogus_path/password"

      # Failure testing is also important
      - name: 'Validate above failure'
        shell: bash
        run: |
          # Check if step above failed as expected
          if [ "${{ steps.failure.outcome }}" == "success" ]; then
            # Error if step above did NOT fail
            echo 'Test expected to fail did NOT fail âŒ'
            echo 'Test expected to fail did NOT fail âŒ' \
              >> "$GITHUB_STEP_SUMMARY"
            exit 1
          else
            # Success if step above failed as expected
            echo "Failure testing passed âœ…"
            echo "Failure testing passed âœ…" >> "$GITHUB_STEP_SUMMARY"
          fi
